Pandas Idioms

In [1]:
import pandas as pd 
import numpy as np
import timeit

df = pd.read_csv('../Semana 2/census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [3]:
#dentro de python tenemos un pequeÃ±o sublenguaje utilizado especialmente en pandas que nos permite enfocar operaciones
#dadas en esta libreria de manera mas sencilla que escribiendo codigo de manera normal como por ejemplo
(df.where(df['SUMLEV'] == 50)
    .dropna()
    .set_index(['STNAME','CTYNAME'])
    .rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'}))

                           SUMLEV  REGION  DIVISION  STATE  COUNTY
STNAME  CTYNAME
Alabama Autauga County       50.0     3.0       6.0    1.0     1.0  \
        Baldwin County       50.0     3.0       6.0    1.0     3.0
        Barbour County       50.0     3.0       6.0    1.0     5.0
        Bibb County          50.0     3.0       6.0    1.0     7.0
        Blount County        50.0     3.0       6.0    1.0     9.0
...                           ...     ...       ...    ...     ...
Wyoming Sweetwater County    50.0     4.0       8.0   56.0    37.0
        Teton County         50.0     4.0       8.0   56.0    39.0
        Uinta County         50.0     4.0       8.0   56.0    41.0
        Washakie County      50.0     4.0       8.0   56.0    43.0
        Weston County        50.0     4.0       8.0   56.0    45.0

                           CENSUS2010POP  Estimates Base 2010
STNAME  CTYNAME
Alabama Autauga County           54571.0              54571.0  \
        Baldwin County          182265.0             182265.0
        Barbour County           27457.0              27457.0
        Bibb County              22915.0              22919.0
        Blount County            57322.0              57322.0
...                                  ...                  ...
Wyoming Sweetwater County        43806.0              43806.0
        Teton County             21294.0              21294.0
        Uinta County             21118.0              21118.0
        Washakie County           8533.0               8533.0
        Weston County             7208.0               7208.0

                           POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012
STNAME  CTYNAME
Alabama Autauga County             54660.0          55253.0          55175.0  \
        Baldwin County            183193.0         186659.0         190396.0
        Barbour County             27341.0          27226.0          27159.0
        Bibb County                22861.0          22733.0          22642.0
        Blount County              57373.0          57711.0          57776.0
...                                    ...              ...              ...
Wyoming Sweetwater County          43593.0          44041.0          45104.0
        Teton County               21297.0          21482.0          21697.0
        Uinta County               21102.0          20912.0          20989.0
        Washakie County             8545.0           8469.0           8443.0
        Weston County               7181.0           7114.0           7065.0

                           ...  RDOMESTICMIG2011  RDOMESTICMIG2012
STNAME  CTYNAME            ...
Alabama Autauga County     ...          7.242091         -2.915927  \
        Baldwin County     ...         14.832960         17.647293
        Barbour County     ...         -4.728132         -2.500690
        Bibb County        ...         -5.527043         -5.068871
        Blount County      ...          1.807375         -1.177622
...                        ...               ...               ...
Wyoming Sweetwater County  ...          1.072643         16.243199
        Teton County       ...         -1.589565          0.972695
        Uinta County       ...        -17.755986         -4.916350
        Washakie County    ...        -11.637475         -0.827815
        Weston County      ...        -11.752361         -8.040059

                           RDOMESTICMIG2013  RDOMESTICMIG2014
STNAME  CTYNAME
Alabama Autauga County            -3.012349          2.265971  \
        Baldwin County            21.845705         19.243287
        Barbour County            -7.056824         -3.904217
        Bibb County               -6.201001         -0.177537
        Blount County             -1.748766         -2.062535
...                                     ...               ...
Wyoming Sweetwater County         -5.339774        -14.252889
        Teton County              19.525929         14.143021
        Uinta County              -6.902954        -14.215862
        Washakie County           -2.013502        -17.781491
        Weston County             12.372583          1.533635

                           RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012
STNAME  CTYNAME
Alabama Autauga County            -2.530799     7.606016    -2.626146  \
        Baldwin County            17.197872    15.844176    18.559627
        Barbour County           -10.543299    -4.874741    -2.758113
        Bibb County                0.177258    -5.088389    -4.363636
        Blount County             -1.369970     1.859511    -0.848580
...                                     ...          ...          ...
Wyoming Sweetwater County        -14.248864     1.255221    16.243199
        Teton County              -0.564849     0.654527     2.408578
        Uinta County             -12.127022   -18.136812    -5.536861
        Washakie County            1.682288   -11.990126    -1.182592
        Weston County              6.935294   -12.032179    -8.040059

                           RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County       -2.722002     2.592270    -2.187333
        Baldwin County       22.727626    20.317142    18.293499
        Barbour County       -7.167664    -3.978583   -10.543299
        Bibb County          -5.403729     0.754533     1.107861
        Blount County        -1.402476    -1.577232    -0.884411
...                                ...          ...          ...
Wyoming Sweetwater County    -5.295460   -14.075283   -14.070195
        Teton County         21.160658    16.308671     1.520747
        Uinta County         -7.521840   -14.740608   -12.606351
        Washakie County      -2.250385   -18.020168     1.441961
        Weston County        12.372583     1.533635     6.935294

[3142 rows x 98 columns]

In [ ]:
#como podemos ver obtenemos una sintaxis un poco diferente a la tradicional y mucho mas "pandorable", sin embargo hay
#que recalcar que tambien podriamos hacer lo mismo con una sintaxis tradicional sin ningun problema
df_aux = df[df['SUMLEV'] == 50]
df_aux.set_index(['STNAME', 'CTYNAME'], inplace=True)
df_aux.rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'})

In [7]:
#Ahora veremos un calculo del rendimiento de cada aproximacion usando la libreria timeit
def first_aproach():
    global df
    
    return (df.where(df['SUMLEV'] == 50)
             .dropna()
             .set_index(['STNAME','CTYNAME'])
             .rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'}))
    
df = pd.read_csv('../Semana 2/census.csv')

timeit.timeit(first_aproach, number = 10)

0.3057730000000447

In [8]:
#ahora veremos el rendimiento de la segunda aproximancion 
def second_aproach():
    global df
    
    df_aux = df[df['SUMLEV'] == 50]
    df_aux.set_index(['STNAME', 'CTYNAME'], inplace=True)
    return df_aux.rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'})

df = pd.read_csv('../Semana 2/census.csv')

timeit.timeit(second_aproach, number = 10)

0.09912009997060522

In [9]:
#como podemos ver el segundo enfoque es mucho mas rapido que el primero, sin embargo es importante conocer ambos dado
#que en ciertos contextos nos podemos encontrar una sintaxis parecida a la primera y asi podremos entender que es lo que se 
#desea hacer

FUNCION APPLY

In [10]:
#En algun momento todos hemos la funcion map que nos permite pasar como parametro una funcion y un iterable(listas, etc) y nos
#devuelve como resultado una lista donde se aplico la funcion en la lista objetivo es asi que un acercamiento en los dataframes
#nos permite encontrar la funcion apply que hace algo parecido pero enfocado en dataframes
def min_max(row):
    data = row[['POPESTIMATE2010', 
                'POPESTIMATE2012', 
                'POPESTIMATE2013', 
                'POPESTIMATE2014', 
                'POPESTIMATE2015']]
    
    return pd.Series({'min' : np.min(data), 'max' : np.max(data)})

In [11]:
df.apply(min_max, axis='columns').head()
#en este caso podemos observar que aplicamos la min_max que sirve para obtener el maximo y minimo de cada columna dadas las columnas especificadas
#dentro de la variable data

       min      max
0  4785161  4858979
1    54660    55347
2   183193   203709
3    26489    27341
4    22512    22861

In [12]:
#y tambien podemos modificar la funcion de otra manera
#En algun momento todos hemos la funcion map que nos permite pasar como parametro una funcion y un iterable(listas, etc) y nos
#devuelve como resultado una lista donde se aplico la funcion en la lista objetivo es asi que un acercamiento en los dataframes
#nos permite encontrar la funcion apply que hace algo parecido pero enfocado en dataframes
def min_max(row):
    data = row[['POPESTIMATE2010', 
                'POPESTIMATE2012', 
                'POPESTIMATE2013', 
                'POPESTIMATE2014', 
                'POPESTIMATE2015']]
    row['max'] = np.max(data)
    row['min'] = np.min(data)
    
    return row

df.apply(min_max,axis='columns')

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,max,min
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594,4858979,4785161
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333,55347,54660
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499,203709,183193
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299,27341,26489
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861,22861,22512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195,45162,43593
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747,23125,21297
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351,21102,20822
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961,8545,8316
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294,7234,7065

In [14]:
#tambien podemos tener un ejemplo del uso de apply junto a lambda
row = ['POPESTIMATE2010', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015']

df.apply(lambda x : np.max(x[row]), axis=1).head()

0    4858979
1      55347
2     203709
3      27341
4      22861
dtype: int64

In [15]:
# La belleza de la funciÃ³n apply radica en que permite flexibilidad para realizar cualquier manipulaciÃ³n deseada,
# ya que la funciÃ³n que pasas a apply puede ser personalizada de la manera que prefieras. Supongamos que queremos
# dividir los estados en cuatro categorÃ­as: Noreste, Medio Oeste, Sur y Oeste. Podemos escribir una funciÃ³n
# personalizada que devuelva la regiÃ³n basada en la informaciÃ³n de las regiones de los estados, que se obtiene de Wikipedia.

def get_state_region(x):
    northeast = ['Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 
                 'Rhode Island','Vermont','New York','New Jersey','Pennsylvania']
    midwest = ['Illinois','Indiana','Michigan','Ohio','Wisconsin','Iowa',
               'Kansas','Minnesota','Missouri','Nebraska','North Dakota',
               'South Dakota']
    south = ['Delaware','Florida','Georgia','Maryland','North Carolina',
             'South Carolina','Virginia','District of Columbia','West Virginia',
             'Alabama','Kentucky','Mississippi','Tennessee','Arkansas',
             'Louisiana','Oklahoma','Texas']
    west = ['Arizona','Colorado','Idaho','Montana','Nevada','New Mexico','Utah',
            'Wyoming','Alaska','California','Hawaii','Oregon','Washington']
    
    if x in northeast:
        return "Northeast"
    elif x in midwest:
        return "Midwest"
    elif x in south:
        return "South"
    else:
        return "West"

In [16]:
df['state_region'] = df['STNAME'].apply(lambda x: get_state_region(x))

In [17]:
df[['STNAME', 'state_region']].head()

    STNAME state_region
0  Alabama        South
1  Alabama        South
2  Alabama        South
3  Alabama        South
4  Alabama        South